# Generated by Django 5.1.3 on 2024-11-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_donation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed'), ('pending', 'pending')], default='pending', max_length=10)),
                ('severity', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('required_help', models.CharField(default='not required', max_length=100)),
            ],
        ),
    ]
